/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <opencv2/opencv.hpp>
/* Header for class com_papakcisoftware_yuztanima_OpencvClass */

using namespace cv;

#ifndef _Included_com_papakcisoftware_yuztanima_OpencvClass
#define _Included_com_papakcisoftware_yuztanima_OpencvClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_papakcisoftware_yuztanima_OpencvClass
 * Method:    faceDetection
 * Signature: (J)V
 */

 void detect(Mat& frame);

JNIEXPORT void JNICALL Java_com_papakcisoftware_yuztanima_OpencvClass_faceDetection
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
